### ISSUE TITLE
Variadic templates

### ISSUE THREAD

**Issue by tripleslash** [Oberon00/luabind#12]
With Visual Studio 2013 and other major compilers out there now supporting variadic templates I think it's worth to consider adding support for those (probably by a #define toggle) instead of those hackish boost iteration macros which probably cause a significant compile time loss.

Opinions?

**Comment by Oberon00** [comment]
I will probably never make this change to luabind as I'm no longer really actively working on the project and will probably only fix bugs.

Instead my interests regarding Lua have turned to [apollo](https://github.com/Oberon00/apollo) which uses variadic templates for functions and also has a far more efficient implementation of them (but it's not production ready, still lacks many of luabind's OO features and *requires* C++11).
