### ISSUE TITLE
Luabind does not compile anymore since merge

### ISSUE THREAD

**Issue by tripleslash** [Oberon00/luabind#18]
It is missing luabind/build_information.hpp.
Is it because I don't know how to use CMake and just copy it all over into a new project?

I tried CMake but it kept telling me that it cannot find lua 5.2 but its right inside the folder...
How do I specify the path to lua and how my library files are named? Because they are not named lua.lib/lua52.lib
Is it possible that you add a .sln/project file for MSVC?

I was reading through the INSTALL file but it seems like its outdated. It just tells me to use CMake, not how to use it.

**Comment by Oberon00** [comment]
The original issue should be resolved with the merge of #19.
