### ISSUE TITLE
LUABIND_SKIP_TESTS ignored

### ISSUE THREAD

**Issue by uppfinnarn** [Oberon00/luabind#24]
According to [the documentation](http://oberon00.github.io/luabind/build-options.html#cmake-options), this is supposed to be how you disable building of unit tests, but the code [instead checks](https://github.com/Oberon00/luabind/blob/master/CMakeLists.txt#L202) for a `BUILD_TESTING` variable.

**Comment by Oberon00** [comment]
In this case, I decided that the code was "right", not the documentation, as `BUILD_TESTING` is a standard CMake option. Fixed by e0fa6d2088fdfa5c584c5c63aece640af27641b2 (and 3227453cf71cea55eb935d1f4dd193ef2017f849).
