### ISSUE TITLE
Crash during luabind::open with luajit 2

### ISSUE THREAD

**Issue by danbulgakov** [Oberon00/luabind#26]
I tried to use it for luajit 2 on Ubuntu 12.04 (boost 1.48).
It crashes on luadind::open.

**Comment by Oberon00** [comment]
I remember there were some problems with the Lua 5.1 compatibility functions. I will look into that.

**Comment by Oberon00** [comment]
Please try again with 72c2ed4ec3763027a7ae8947ed70299e0500ad3d.

**Comment by danbulgakov** [comment]
It works, great! Thanks a lot.

**Comment by Oberon00** [comment]
Good to hear!
