### ISSUE TITLE
Can't compile in c++11 mode

### ISSUE THREAD

**Issue by Bertram25** [Oberon00/luabind#27]
```
git submodule update --init --recursive
Submodule 'cmake/cxx11' (git://anongit.kde.org/scratch/dakon/cmake-cxx11.git) recorded for path 'cmake/cxx11'
Cloning in 'cmake/cxx11'...
fatal: remote error: access denied or repository not exported: /scratch/dakon/cmake-cxx11.git
```

I must also say I'm a bit dumbfounded to see that one needs a module to compile in c++11 mode. Could this be a simple option?

Best regards,

**Comment by Oberon00** [comment]
Initially it was a just an option. AFAIR the module usage was introduced to provide better default options. I will look into that.

**Comment by Bertram25** [comment]
Thanks a lot for all the fixes regarding that part!
